package outlook

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

// DraftOptions controls how the Outlook compose window is opened.
type DraftOptions struct {
	Subject  string
	HTMLBody string
	To       []string
	CC       []string
	AutoSend bool // if true, sends immediately without showing window
}

// OpenDraft opens an Outlook compose window pre-filled with the given content.
// It writes the HTML body to a UTF-8 temp file and a PowerShell script that
// reads it — this ensures Nordic and other special characters are handled correctly.
func OpenDraft(opts DraftOptions) error {
	// Write HTML body to a separate UTF-8 temp file.
	// This avoids embedding special characters directly in the PS script string,
	// which can cause encoding issues with Nordic letters (öäõü etc.)
	htmlFile, err := os.CreateTemp("", "release-notifier-body-*.html")
	if err != nil {
		return fmt.Errorf("creating temp HTML file: %w", err)
	}
	defer os.Remove(htmlFile.Name())

	if _, err := htmlFile.WriteString(opts.HTMLBody); err != nil {
		htmlFile.Close()
		return fmt.Errorf("writing HTML body: %w", err)
	}
	htmlFile.Close()

	// Build and write the PowerShell script.
	script, err := buildScript(opts, htmlFile.Name())
	if err != nil {
		return fmt.Errorf("building powershell script: %w", err)
	}

	psFile, err := os.CreateTemp("", "release-notifier-*.ps1")
	if err != nil {
		return fmt.Errorf("creating temp script file: %w", err)
	}
	defer os.Remove(psFile.Name())

	// Write PS script as UTF-8 with BOM — PowerShell requires BOM to correctly
	// read UTF-8 encoded .ps1 files on Windows
	bom := []byte{0xEF, 0xBB, 0xBF}
	if _, err := psFile.Write(bom); err != nil {
		psFile.Close()
		return fmt.Errorf("writing BOM: %w", err)
	}
	if _, err := psFile.WriteString(script); err != nil {
		psFile.Close()
		return fmt.Errorf("writing script: %w", err)
	}
	psFile.Close()

	cmd := exec.Command(
		"powershell",
		"-NoProfile",
		"-ExecutionPolicy", "Bypass",
		"-File", filepath.ToSlash(psFile.Name()),
	)

	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("powershell error: %w\nOutput: %s", err, string(out))
	}

	return nil
}

// buildScript renders the PowerShell script. The HTML body is read from a
// temp file rather than embedded in the script to preserve UTF-8 encoding.
func buildScript(opts DraftOptions, htmlFilePath string) (string, error) {
	const psTmpl = `
# Release Notifier — Outlook COM Draft
# Auto-generated by release-notifier

$ErrorActionPreference = 'Stop'

# Read HTML body from UTF-8 file to preserve special characters (öäõü etc.)
$htmlBody = [System.IO.File]::ReadAllText('{{.HTMLFilePath}}', [System.Text.Encoding]::UTF8)

try {
    $outlook = New-Object -ComObject Outlook.Application
} catch {
    Write-Error "Could not start Outlook. Is it installed and configured?"
    exit 1
}

$mail = $outlook.CreateItem(0)  # 0 = olMailItem

$mail.Subject = @'
{{.Subject}}
'@

$mail.HTMLBody = $htmlBody

{{- if .To}}
$mail.To = '{{.ToStr}}'
{{- end}}

{{- if .CC}}
$mail.CC = '{{.CCStr}}'
{{- end}}

{{- if .AutoSend}}
$mail.Send()
Write-Host "Email sent successfully."
{{- else}}
$mail.Display()  # Opens the compose window for review
{{- end}}
`

	// Normalise path separators for PowerShell
	safePath := strings.ReplaceAll(htmlFilePath, `\`, `\\`)

	t, err := template.New("ps").Parse(psTmpl)
	if err != nil {
		return "", err
	}

	data := struct {
		Subject      string
		HTMLFilePath string
		To           []string
		CC           []string
		ToStr        string
		CCStr        string
		AutoSend     bool
	}{
		Subject:      opts.Subject,
		HTMLFilePath: safePath,
		To:           opts.To,
		CC:           opts.CC,
		ToStr:        strings.Join(opts.To, "; "),
		CCStr:        strings.Join(opts.CC, "; "),
		AutoSend:     opts.AutoSend,
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
