package outlook

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"bytes"
)

// DraftOptions controls how the Outlook compose window is opened.
type DraftOptions struct {
	Subject    string
	HTMLBody   string
	To         []string
	CC         []string
	AutoSend   bool   // if true, sends immediately without showing window
}

// OpenDraft opens an Outlook compose window pre-filled with the given content.
// It writes a temporary PowerShell script and executes it.
func OpenDraft(opts DraftOptions) error {
	script, err := buildScript(opts)
	if err != nil {
		return fmt.Errorf("building powershell script: %w", err)
	}

	// Write to temp file — avoids command-line escaping issues with large HTML bodies
	tmpFile, err := os.CreateTemp("", "release-notifier-*.ps1")
	if err != nil {
		return fmt.Errorf("creating temp script file: %w", err)
	}
	defer os.Remove(tmpFile.Name())

	if _, err := tmpFile.WriteString(script); err != nil {
		tmpFile.Close()
		return fmt.Errorf("writing script: %w", err)
	}
	tmpFile.Close()

	// Run with -ExecutionPolicy Bypass so it works without system policy changes
	cmd := exec.Command(
		"powershell",
		"-NoProfile",
		"-ExecutionPolicy", "Bypass",
		"-File", filepath.ToSlash(tmpFile.Name()),
	)

	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("powershell error: %w\nOutput: %s", err, string(out))
	}

	return nil
}

// buildScript renders the PowerShell template with the given options.
func buildScript(opts DraftOptions) (string, error) {
	const psTmpl = `
# Release Notifier — Outlook COM Draft
# Auto-generated by release-notifier

$ErrorActionPreference = 'Stop'

try {
    $outlook = New-Object -ComObject Outlook.Application
} catch {
    Write-Error "Could not start Outlook. Is it installed and configured?"
    exit 1
}

$mail = $outlook.CreateItem(0)  # 0 = olMailItem

$mail.Subject = @'
{{.Subject}}
'@

$mail.HTMLBody = @'
{{.HTMLBody}}
'@

{{- if .To}}
$mail.To = '{{.ToStr}}'
{{- end}}

{{- if .CC}}
$mail.CC = '{{.CCStr}}'
{{- end}}

{{- if .AutoSend}}
$mail.Send()
Write-Host "Email sent successfully."
{{- else}}
$mail.Display()  # Opens the compose window for review
{{- end}}
`

	t, err := template.New("ps").Parse(psTmpl)
	if err != nil {
		return "", err
	}

	data := struct {
		Subject  string
		HTMLBody string
		To       []string
		CC       []string
		ToStr    string
		CCStr    string
		AutoSend bool
	}{
		Subject:  opts.Subject,
		HTMLBody: opts.HTMLBody,
		To:       opts.To,
		CC:       opts.CC,
		ToStr:    strings.Join(opts.To, "; "),
		CCStr:    strings.Join(opts.CC, "; "),
		AutoSend: opts.AutoSend,
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
